### ISSUE TITLE
Convert default model from mmdet3d

### ISSUE THREAD

**Issue by evgeniishch** [Tartisan/MMDet3d-CenterPoint#1]
Hello @Tartisan @wangtao! First, thank you for your great work! 
I tried to use your code to convert a default centerpoint-pointpillars model from mmdet3d repo (specifically, [this one](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/centerpoint/centerpoint_02pillar_second_secfpn_4x8_cyclic_20e_nus.py)). I first generated the .onnx files using your [export_onnx.py](https://github.com/Tartisan/mmdetection3d/blob/master/tools/onnx_tools/centerpoint/export_onnx.py) script and then built and launched your demo pipeline. 

However, unfortunately I run into this 'illegal memory access' error
```
Building TRT engine.
the platform supports Fp16, use Fp16.
WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.4.2
WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.4.2
Building TRT engine.
the platform supports Fp16, use Fp16.
WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.4.2
WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.4.2
WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.4.2
WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.4.2
num points: 155686
find pillar num: 25557
pillar feature dim: 64
backbone_map_size: 262144
GPUassert: an illegal memory access was encountered /home/eashchagin/MMDet3d-CenterPoint/centerpoint/centerpoint.cc 365
Unexpected Internal Error: [virtualMemoryBuffer.cpp::~StdVirtualMemoryBufferImpl::121] Error Code 1: Cuda Runtime (driver shutting down)
Unexpected Internal Error: [virtualMemoryBuffer.cpp::~StdVirtualMemoryBufferImpl::121] Error Code 1: Cuda Runtime (driver shutting down)
```

I suppose the issue could be with this [config](https://github.com/Tartisan/MMDet3d-CenterPoint/blob/master/cfgs/centerpoint_pillar02_secfpn_cyclic_aicv.yaml) or C++ implementation of centerpoint inference which might be tailored for the model which you are using. 
I've checked the differences in models which we are using, i.e. [your model](https://github.com/Tartisan/mmdetection3d/blob/master/configs/_base_/models/centerpoint_02pillar_second_secfpn_aicv-4class-voxel0.2-80m.py) and [mine](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/centerpoint_02pillar_second_secfpn_nus.py#L44). The differences which I've found are 

- number of lidar point features used ([you use 4](https://github.com/Tartisan/mmdetection3d/blob/9741eedfaea0540957941f7f4b5923f01f516b8b/configs/_base_/models/centerpoint_02pillar_second_secfpn_aicv-4class-voxel0.2-80m.py#L8) and [i use 5](https://github.com/open-mmlab/mmdetection3d/blob/bc0a76c030bd48b761c0c2f03f033e7e0a819d44/configs/_base_/models/centerpoint_02pillar_second_secfpn_nus.py#L8))
- number of classes and class heads (I predict 10 and you predict 4)
- [Output dimension of PointPillarsScatter layer](https://github.com/open-mmlab/mmdetection3d/blob/bc0a76c030bd48b761c0c2f03f033e7e0a819d44/configs/_base_/models/centerpoint_02pillar_second_secfpn_nus.py#L15)
- I predict [vecolity](https://github.com/open-mmlab/mmdetection3d/blob/bc0a76c030bd48b761c0c2f03f033e7e0a819d44/configs/_base_/models/centerpoint_02pillar_second_secfpn_nus.py#L44) and you don't 

What should I change to successfully run your pipeline with my model?
Best wishes, Evgenii

**Comment by Tartisan** [comment]
the point feature you use 5, so the extended feature after PillarFeatureNet is (5 + 6 = 11), you should change the GatherFeatureKernel in preprocess.cu

**Comment by evgeniishch** [comment]
Thank you, I will let you know if I succeed !

**Comment by HULoaf** [comment]
> Thank you, I will let you know if I succeed !

Hi, i am facing the problem as same as yours, did you succeed? please help me! Appreciate!

**Comment by HULoaf** [comment]
> Thank you, I will let you know if I succeed !

please help me! tears of grateful!
